# Generated by Django 5.2.17 on 2026-08-21 19:55

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_birth", models.DateField()),
                (
                    "nicknames",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Known nickname variants (e.g., ['Bill', 'Billy'] for William)",
                        size=None,
                    ),
                ),
                (
                    "person_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Links records representing the same real person (same DOB, name variants, typos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
    ]
