# Generated by Django 5.2.16 on 2026-07-08 15:12

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "nicknames",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Known nickname variants (e.g., ['Bill', 'Billy'] for William)",
                        size=None,
                    ),
                ),
                (
                    "first_name_phonetic",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        help_text="Soundex + DM tokens for first name and nickname variants",
                        size=None,
                    ),
                ),
                (
                    "last_name_phonetic",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        help_text="Soundex + DM tokens for last name",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["first_name_phonetic"], name="idx_person_first_phonetic"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["last_name_phonetic"], name="idx_person_last_phonetic"
                    ),
                    models.Index(
                        django.contrib.postgres.indexes.OpClass(models.F("last_name"), name="text_pattern_ops"),
                        name="idx_person_last_name_prefix",
                    ),
                ],
            },
        ),
    ]
