# Generated by Django 5.2.16 on 2026-08-07 20:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_enable_extensions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="person",
            name="idx_person_last_name_prefix",
        ),
        migrations.AddIndex(
            model_name="person",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["last_name"], name="idx_person_last_name_trgm", opclasses=["gist_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["first_name"], name="idx_person_first_name_trgm", opclasses=["gist_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                django.contrib.postgres.indexes.OpClass(
                    models.Func(models.F("last_name"), function="UPPER"), name="text_pattern_ops"
                ),
                django.contrib.postgres.indexes.OpClass(
                    models.Func(models.F("first_name"), function="UPPER"), name="text_pattern_ops"
                ),
                name="idx_person_name_prefix",
            ),
        ),
    ]
