# Generated by Django 5.2.16 on 2026-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_person_idx_person_last_name_prefix_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date_of_birth'], name='idx_person_date_of_birth'),
        ),
    ]
