# Generated by Django 5.2.16 on 2026-08-14 22:21

import uuid

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0006_add_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="person_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Links records representing the same real person (same DOB, name variants, typos)",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                models.Func(models.F("first_name"), function="SOUNDEX", template="SOUNDEX(UPPER(%(expressions)s))"),
                name="idx_person_first_name_soundex",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                models.Func(models.F("last_name"), function="SOUNDEX", template="SOUNDEX(UPPER(%(expressions)s))"),
                name="idx_person_last_name_soundex",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=django.contrib.postgres.indexes.GinIndex(
                models.Func(
                    models.F("first_name"),
                    function="DAITCH_MOKOTOFF",
                    template="DAITCH_MOKOTOFF(UPPER(%(expressions)s))",
                ),
                name="idx_person_first_name_dm",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=django.contrib.postgres.indexes.GinIndex(
                models.Func(
                    models.F("last_name"),
                    function="DAITCH_MOKOTOFF",
                    template="DAITCH_MOKOTOFF(UPPER(%(expressions)s))",
                ),
                name="idx_person_last_name_dm",
            ),
        ),
    ]
