# Generated by Django 5.2.16 on 2026-08-20 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0007_alter_person_person_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="CourtRecord",
        ),
        migrations.AlterModelOptions(
            name="courtrecord",
            options={"verbose_name": "Court Record", "verbose_name_plural": "Court Records"},
        ),
    ]
